Adding Word Count
clearfeld/dev-tool-box pull request #8
Opened 2024-02-04 11:58 UTC by AaronPatterson1

2024-02-05 01:20 UTC, clearfeld requested changes

2024-02-05 01:20 UTC, clearfeld commented on src/tools/strings/word-count/index.tsx
> +	}, [text]);
This seems messy, cramming all the info into one string. Can you split this up into individual pieces of state and display the pieces of state individually instead of just one textarea.

2024-02-05 01:20 UTC, clearfeld commented on src/tools/strings/word-count/index.tsx
> +						/>
Pretty print the pieces of state, instead of just displaying the string in a disabled text area.

2024-02-05 01:20 UTC, clearfeld commented on src/tools/strings/word-count/index.tsx
> +Paragraph Count: ${lineCount}
Could you also run the biome js formatter before commiting the code.

2024-02-11 16:39 UTC, clearfeld approved these changes

2024-02-11 16:39 UTC, clearfeld commented on src/tools/strings/word-count/index.tsx
> +	function  onChangeText(e: BaseSyntheticEvent): void {
`BaseSyntheticEvent` is the wrong type use `React.ChangeEvent<HTMLTextAreaElement>` instead.

2024-02-11 16:39 UTC, clearfeld commented on src/tools/strings/word-count/index.tsx
> +import { BaseSyntheticEvent, useEffect, useReducer, useState } from "react";
BaseSyntheticEvent can be removed.

2024-02-12 23:46 UTC, AaronPatterson1 commented on src/tools/strings/word-count/index.tsx
> +import { BaseSyntheticEvent, useEffect, useReducer, useState } from "react";
Done, please check.

2024-02-13 03:44 UTC, clearfeld approved these changes

2024-02-13 03:44 UTC, merged